spring:
  datasource:
    driver-class-name: org.h2.Driver    
    url: jdbc:h2:mem:sales-db
    username: sa
    password: 
      hibernate:
#        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true